# Generated by Django 2.1.7 on 2019-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190319_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='scar',
            name='c_date',
            field=models.DateField(null=True),
        ),
    ]
