# Generated by Django 2.1.7 on 2019-03-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190322_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[(1, '普通会员'), (2, 'VIP'), (3, 'SVIP')], default='普通会员', max_length=32),
        ),
    ]
