# Generated by Django 2.1.7 on 2019-03-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190322_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default='男', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, '普通会员'), (2, 'VIP'), (3, 'SVIP')], default='普通会员', max_length=32),
        ),
    ]
