# Generated by Django 2.1.7 on 2019-03-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190322_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[('1', '普通会员'), ('2', 'VIP'), ('3', 'SVIP')], default='1', max_length=32),
        ),
    ]
