# Generated by Django 2.1.7 on 2019-04-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=128)),
                ('server_num', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('cpus', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('disk', models.IntegerField(default=0)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线'), ('normal', '正常'), ('abnormal', '异常')], max_length=16)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
