# Generated by Django 2.1.7 on 2019-03-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Userhobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('age', models.SmallIntegerField(default=12)),
                ('sex', models.CharField(choices=[(1, '男'), (2, '女')], default='男', max_length=20)),
                ('c_time', models.DateTimeField(null=True)),
                ('hobby', models.ManyToManyField(related_name='userhobby', to='app1.Userinfo')),
                ('ug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='app1.Usergroup')),
            ],
        ),
    ]
