# Generated by Django 2.1.7 on 2019-03-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Userhobby',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ug',
        ),
        migrations.DeleteModel(
            name='Usergroup',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Colors'),
        ),
        migrations.AddField(
            model_name='child',
            name='favor',
            field=models.ManyToManyField(to='app1.Colors'),
        ),
        migrations.AddField(
            model_name='ball',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.Colors'),
        ),
    ]
